name: Publish to NPM

on:
  workflow_call:
    inputs:
      library:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Instal dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:prod

      - name: Build package
        run: npm run build ${{ inputs.library }}

      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  publish-to-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Publish to NPM
        working-directory: ./dist/${{ inputs.library }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
