on:
  push:
    branches:
      - main
    # path: 'projects/${{ inputs.library }}'

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/npm-publish.yml@main
    with:
      library: red-button
