name: Publish to NPM

on:
  push:
    branches:
      - main
    paths:
      - 'projects/red-button'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Instal dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:prod

      - name: Build package
        run: npm run build red-button

  publish-to-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3

      # - name: Install node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      # - run: npm ci

      - name: Download build
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist

      - name: Publish to NPM
        working-directory: ./dist/red-button
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
