on:
  workflow_dispatch:
  push:
    branches:
      - main
    # path: 'projects/${{ inputs.library }}'

jobs:
  red-button:
    uses: ./.github/workflows/npm-publish.yml
    with:
      library: red-button
    secrets: inherit
